#ifndef PEGR_TEST_TESTS_HPP
#define PEGR_TEST_TESTS_HPP

#include <functional>

/*******************************************************************************
 * WARNING! This file is automatically generated by a Python script! Any manual
 * edits to this file are likely to be overwritten automatically! To make any
 * changes other than adding/removing tests, modify TestsBoilerplate.hpp
 * located in the tool/ dir and run GenerateTestList.py
 ******************************************************************************/

namespace pegr {
namespace Test {

/*### TESTS FWD ###*/

struct NamedTest {
    const char* m_name;
    std::function<void()> m_test;
};

const NamedTest n_tests[] = {
    
    {"Testing Framework", [](){}},

/*### TESTS LIST ###*/
    
    // Sentinel
    {nullptr, std::function<void()>()}
};

struct NamedLuaTest {
    const char* m_name;
    const char* m_lua_file;
};

const NamedLuaTest n_lua_tests[] = {
    
/*### LUA TESTS LIST ###*/
    
    // Sentinel
    {nullptr, nullptr}
};

} // namespace pegr
} // namespace Test

#endif // PEGR_TEST_TESTS_HPP
